import type { IconName, Layer, Swatch } from "@/lib/types";

/** Trusted first-party rich text (<b>, <br>, <span class="g|h">) from content/decks/*.json. */
export function Rich({ html, as: Tag = "span", className }: { html: string; as?: "span" | "p" | "h1" | "h2" | "div"; className?: string }) {
  return <Tag className={className} dangerouslySetInnerHTML={{ __html: html }} />;
}

/** Inline SVG artwork generated by tools/generator (kept inline so CSS animations apply). */
export function Art({ svg, className = "fig", swipe }: { svg: string; className?: string; swipe?: string }) {
  return (
    <>
      <div className={className} dangerouslySetInnerHTML={{ __html: svg }} />
      {swipe ? <span className="swipe">{swipe}</span> : null}
    </>
  );
}

const ICONS: Record<IconName, string> = {
  bolt: '<path d="M13 2 4 14h7l-1 8 9-12h-7z"/>',
  flame: '<path d="M12 22c4 0 7-3 7-7 0-4-3-6-4-10-2 2-3 4-3 6-1-1-2-2-2-4-3 3-5 5-5 8 0 4 3 7 7 7z"/>',
  leaf: '<path d="M4 20c0-9 6-15 16-16-1 10-7 16-16 16zM4 20l8-8"/>',
  globe: '<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 3 15 0 18M12 3c-3 3-3 15 0 18"/>',
  users: '<circle cx="9" cy="8" r="3.5"/><path d="M2 20c1-4 4-6 7-6s6 2 7 6"/><circle cx="17" cy="9" r="2.5"/><path d="M17 14c2 0 4 2 5 5"/>',
  rupee: '<path d="M6 4h12M6 9h12M6 4c7 0 7 10 0 10l9 7"/>',
  shield: '<path d="M12 3 4 6v6c0 5 4 8 8 9 4-1 8-4 8-9V6z"/><path d="m8.5 12 2.5 2.5 4.5-5"/>',
  box: '<path d="M3 7l9-4 9 4-9 4zM3 7v10l9 4 9-4V7M12 11v10"/>',
  chart: '<path d="M4 20V4M4 20h16M8 16v-4M12 16V8M16 16v-7"/>',
};

export function Icon({ name }: { name: IconName }) {
  return <svg className="ico" viewBox="0 0 24 24" aria-hidden="true" dangerouslySetInnerHTML={{ __html: ICONS[name] }} />;
}

export const layerClass = (l: Layer) => `c-${l}`;
export const swatch = (s: Swatch) => `var(--${s})`;
export const pad2 = (n: number) => String(n).padStart(2, "0");

export function Eyebrow({ lead, rest, color }: { lead: string; rest?: string; color?: string }) {
  return (
    <div className="eb" style={color ? { color } : undefined}>
      {lead} {rest ? <i>/ {rest}</i> : null}
    </div>
  );
}

export function Card({ icon, title, text }: { icon: IconName; title: string; text: string }) {
  return (
    <div className="card">
      <Icon name={icon} />
      <h3>{title}</h3>
      <p>{text}</p>
    </div>
  );
}

export function Stats({ items }: { items: [string, string][] }) {
  return (
    <div className="stats">
      {items.map(([v, l]) => (
        <div className="stat" key={l}>
          <b>{v}</b>
          <span className="lab">{l}</span>
        </div>
      ))}
    </div>
  );
}

export function Legend({ items }: { items: { label: string; style: React.CSSProperties }[] }) {
  return (
    <div className="legend">
      {items.map((i) => (
        <span key={i.label}>
          <i className="sw" style={i.style} />
          {i.label}
        </span>
      ))}
    </div>
  );
}

export function Page({ n, total, left, right, short, children }: { n: number; total: number; left: string; right: string; short: string; children: React.ReactNode }) {
  return (
    <section className="pg" id={`p${pad2(n)}`} aria-label={left}>
      <div className="hd">
        <span>{pad2(n)} / {left}</span>
        <span>{right}</span>
      </div>
      {children}
      <div className="ft">
        <span>jouleWise · decarbonisation stack · {short}</span>
        <span>{pad2(n)} / {pad2(total)}</span>
      </div>
    </section>
  );
}
