/** Shape of content/decks/<slug>.json — produced by tools/generator/export.py.
 *  Fields ending in `Html` may contain <b>, <br> and <span class="g|h"> only (trusted, first-party copy).
 *  `svg.*` are complete inline SVG documents generated by tools/generator. */
export type Layer = "power" | "heat" | "data" | "esg";
export type Swatch = "green" | "heat" | "data" | "esg";
export type IconName = "bolt" | "flame" | "leaf" | "globe" | "users" | "rupee" | "shield" | "box" | "chart";
export type Pair = [string, string];

export interface DeckData {
  slug: string;
  short: string;
  meta: { title: string; description: string };
  cover: { eyebrow: string; titleHtml: string; sub: string; lede: string; stats: Pair[] };
  execSummary: { titleHtml: string; rows: Pair[]; outcomes: Pair[]; note: string };
  whyNow: { titleHtml: string; lede: string; drivers: { icon: IconName; title: string; text: string }[] };
  stack: { titleHtml: string; lede: string; items: { layer: Layer; title: string; text: string }[]; calloutHtml: string };
  supplyChain: { eyebrow: string; titleHtml: string; lede: string; note: string;
    points: { n: number; layer: Layer; tag: string; title: string; text: string }[] };
  power: { titleHtml: string; lede: string; calloutHtml: string; steps: { title: string; text: string; outcome: string }[] };
  heatPump101: { titleHtml: string; lede: string; copNote: string; liftNote: string; lifts: Pair[]; faq: Pair[];
    balance: { name: string; in: [string, number][]; inLabel: string; out: number; outLabel: string }[] };
  heat: { titleHtml: string; lede: string;
    loads: { name: string; sub: string; min: number; max: number; heatPump: boolean }[];
    cards: { icon: IconName; title: string; text: string }[] };
  economics: { titleHtml: string; lede: string; note: string;
    rows: { name: string; sub: string; costPerKwhTh: number; co2PerKwhTh: number; kind: "fuel" | "grid" | "green" }[] };
  ergos: { titleHtml: string; lede: string; cards: { icon: IconName; title: string; text: string }[];
    cockpit: { title: string; tiles: { label: string; value: string; valueColor: string; sub: string; subColor: string }[];
      ops: { color: string; icon: string; text: string }[] } };
  esgos: { titleHtml: string; lede: string; outputsLabel: string; outputs: string[]; calloutHtml: string;
    modes: { color: Swatch; kicker: string; title: string; text: string }[] };
  models: { titleHtml: string; lede: string; note: string;
    items: { color: Swatch; kicker: string; title: string; text: string; rows: Pair[] }[] };
  roadmap: { titleHtml: string; note: string; steps: { title: string; when: string; text: string; outcome: string }[] };
  trackRecord: { titleHtml: string; lede: string; note: string; clients: [string, string, string][]; stats: Pair[] };
  contact: { titleHtml: string; lede: string; disclaimer: string;
    people: { area: string; color: Swatch; name: string; email: string; phone: string | null }[];
    company: { site: string; legal: string } };
  svg: { coverStack: string; loop: string; cycle: string; scene: string; dayChart: string };
  /** The series svg.dayChart is drawn from, so the chart can be scrubbed. See build.py day_data(). */
  dayData: {
    geo: { w: number; h: number; l: number; r: number; t: number; b: number; max: number; n: number };
    unit: string;
    hours: number[]; base: number[]; hp: number[]; load: number[];
    wind: number[]; solar: number[]; bess: number[]; market: number[];
  };
}
