G = '<span class="g">%s</span>'

AUTO = dict(
    short="Automotive", slug="automotive", scene="automotive",
    cover_h2="For automotive plants.",
    cover_p="One provider for green power, green heat and the data that proves both — from press shop to paint shop to dispatch.",
    exec=dict(
        headline="Two energy bills.<br>" + G % "One plan to cut both.",
        situation="An automotive plant pays two energy bills. Electricity runs presses, welding robots, compressed air and paint-shop HVAC; fuel — PNG, LPG or diesel — heats pretreatment baths, washers and ovens. OEMs increasingly ask suppliers for Scope 1 and 2 numbers and a reduction plan, and EU importers of steel and aluminium goods need embedded-emissions data under CBAM.",
        value="Up to 25% lower power cost on DISCOM tariff and up to 65% renewable share (reported, year 1 of ergOS). Heat pumps then displace fuel on pretreatment, washers and hot water — on green power, that heat is close to zero-carbon and a fraction of the cost of fuel-fired heat.",
        first="A four-week decarbonisation baseline on one plant: power bills, load survey, fuel records and portable heat metering in the paint shop — ending in one business case for power, heat and ESG.",
    ),
    why_h="The customer is<br>" + G % "counting your carbon.",
    why_p="For a vehicle or component maker, decarbonisation has moved from a CSR line to a sourcing condition. Six pressures point at the same metered data.",
    drivers=[
        ("users", "OEM supplier targets", "Vehicle makers are setting decarbonisation expectations for their supply base. Suppliers with metered Scope 1 and 2 data and a credible plan hold their place on the approved list."),
        ("globe", "Exports and CBAM", "EU importers of iron, steel and aluminium goods report embedded emissions under CBAM. Component exporters in scope need plant-level, verifiable data."),
        ("rupee", "Energy cost", "The paint shop is among the largest energy users in a vehicle plant — heat, booth HVAC and ovens. Every rupee off power and fuel goes straight to margin."),
        ("shield", "Disclosure", "BRSR Core-format reporting and value-chain disclosure put your energy and emissions in your customers' reports as well as your own."),
        ("bolt", "Electrification", "As the product line electrifies, the carbon in making it becomes the visible number. Green power and green heat cut it where it is measured — on the plant meter."),
        ("leaf", "Carbon markets", "India's Carbon Credit Trading Scheme sets emission-intensity targets sector by sector. Plants that measure now are ready when their sector or supply chain is covered."),
    ],
    chain_eb="Press to dispatch",
    chain_h="Every shop<br>has a lever.",
    chain_p="Coils arrive, presses stamp, robots weld, the paint shop heats and cools, assembly builds, carriers leave. jouleWise acts at ten points across the plant — four layers, one plan.",
    marks=[
        (1, "power", "Green sourcing", "Intrastate and ISTS solar and wind contracted through open access, routed for the lowest landed cost."),
        (2, "power", "Connectivity and metering", "Open access approvals, connection agreement and ABT metering at the plant incomer."),
        (3, "power", "Rooftop solar", "Press and body shop roofs carry behind-the-meter solar, sized from measured load."),
        (4, "power", "Battery storage", "LFP storage moves midday solar into the evening shift and shaves peak demand."),
        (5, "heat", "Heat pumps on pretreatment", "Degreasing and conversion baths heated by heat pumps instead of PNG or diesel burners."),
        (6, "heat", "Thermal storage", "Hot water store charged in solar blocks, drawn across all shifts."),
        (7, "heat", "Waste heat recovery", "Compressor-house and chiller-condenser heat lifted back to process temperature."),
        (8, "data", "ergOS control", "15-minute metering of power, heat, fuel and water; forecasting, trading and heat dispatch."),
        (9, "esg", "Inbound steel and aluminium", "Supplier data and embedded emissions for Scope 3 and CBAM reporting."),
        (10, "esg", "Outbound and customers", "Per-part carbon, OEM questionnaires and BRSR Core-format disclosure from esgOS."),
    ],
    power_p="Presses, welding lines, compressed air and paint-shop HVAC set a two- or three-shift load. We build the green portfolio to that profile — and move heat pump load into the solar hours, where green power is cheapest.",
    load=(85, 38, 24), shift=(6, 23), hp_window=(9, 16),
    heat_p="Most paint-shop heat is low-temperature: cleaning baths, conversion coating, booth air and washers sit well below 120 °C. Industrial heat pumps serve those loads with electricity — so as power gets cheaper and greener, so does every unit of heat.",
    heat_loads=[
        ("Pretreatment degreasing", "alkaline cleaning baths", 45, 60),
        ("Conversion coating", "zirconium or phosphate", 30, 55),
        ("ED bath and rinses", "cooling the bath, heating rinse water", 28, 35),
        ("Paint booth air", "heating and humidity control", 20, 30),
        ("Parts washers", "machining and assembly lines", 50, 80),
        ("Canteen and hot water", "kitchens, showers, laundry", 55, 65),
        ("Sealer and PVC ovens", "remain on existing burners", 130, 160),
        ("ED and topcoat ovens", "remain on existing burners", 140, 190),
    ],
    heat_src="Compressed-air compressors, ED bath and chiller condensers, oven and booth exhaust — heat you already pay for, lifted back to process temperature.",
    heat_dual="The ED bath and paint-shop HVAC need cooling while pretreatment needs heat. One heat pump serves both — the cooling load becomes the heat source.",
    cop=4.0, cop_note="hot water near 60 °C for pretreatment, lifted from compressor and chiller waste heat",
    cockpit=dict(title="Plant 1 · paint shop + utilities", tiles=[
        ("RE share MTD", "var(--green)", "64%", "var(--green)", "▲ open access"),
        ("Landed power", "var(--ink)", "₹5.4/kWh", "var(--green)", "▼ vs DISCOM"),
        ("Heat pump COP", "var(--heat)", "3.9", "var(--mute)", "HP-1 · HP-2"),
        ("Thermal store", "var(--heat)", "78%", "var(--mute)", "charging · solar block"),
        ("PNG avoided MTD", "var(--ink)", "41,200 SCM", "var(--green)", "▲ vs baseline"),
        ("CO₂ avoided MTD", "var(--ink)", "96 t", "var(--green)", "Scope 1 + 2"),
    ], ops=[
        ("var(--green)", "✓", "Day-ahead schedule sent to SLDC at 09:58"),
        ("var(--green)", "✓", "GDAM bids cleared for blocks 37–64"),
        ("var(--heat)", "●", "HP-2 charging the store in solar blocks until 15:30"),
        ("var(--esg)", "!", "Pretreatment kWh per body +6% vs 30-day average — owner notified"),
    ]),
    esg_out=[
        "BRSR and BRSR Core-format disclosures",
        "OEM supplier sustainability questionnaires and Scope 3 data requests",
        "CBAM embedded-emissions data for iron, steel and aluminium goods exported to the EU",
        "Carbon footprint per part and per vehicle set",
        "CDP climate response and assurance support",
        "Green attribute tracking — iREC eligibility for renewable consumption",
        "Emission-intensity baseline for the Carbon Credit Trading Scheme",
        "Packaging EPR, consents and licence calendar",
    ],
    roadmap2="RE-100 power plan, heat pump shortlist for pretreatment, washers and hot water, and the ESG data map — in one business case.",
    roadmap4="One heat pump and thermal store on pretreatment, metered on ergOS; then washers, booth air and hot water across shops.",
)

PHARMA = dict(
    short="Pharma", slug="pharma", scene="pharma",
    cover_h2="For pharma and API plants.",
    cover_p="One provider for green power, green heat and the data that proves both — from reactor jackets to cleanroom HVAC to the cold chain.",
    exec=dict(
        headline="Heating and cooling<br>" + G % "at the same time.",
        situation="A pharma site runs round the clock: cleanroom HVAC, chilled water for reactors, purified-water loops and steam for jackets, dryers and sanitisation. Much of that heat comes from boilers for loads well below 120 °C, while chillers next door reject heat to cooling towers. Global customers increasingly ask API and formulation suppliers for renewable share, Scope 1 and 2 data and reduction targets.",
        value="Up to 25% lower power cost on DISCOM tariff and up to 65% renewable share (reported, year 1 of ergOS). Heat pumps on the chilled-water return then deliver heating and cooling from the same kWh — displacing boiler fuel on jacket loops, HVAC reheat and water systems.",
        first="A four-week decarbonisation baseline on one site: power bills, load survey, fuel and steam records, and portable heat metering on jacket loops, HVAC reheat and water systems — ending in one business case for power, heat and ESG.",
    ),
    why_h="Your buyers are<br>" + G % "auditing your utilities.",
    why_p="For an API, formulation or CDMO site, the carbon in the product is now part of the commercial conversation. Six pressures point at the same metered data.",
    drivers=[
        ("users", "Global customer programmes", "Multinational pharma buyers run supplier sustainability programmes that ask API and CDMO partners for renewable power, Scope 1 and 2 data and targets."),
        ("globe", "Regulated export markets", "Health systems in Europe increasingly weigh supplier carbon in procurement — NHS England, for example, asks suppliers for carbon reduction plans."),
        ("rupee", "Utility cost", "Round-the-clock HVAC, chilled water, purified water and steam make utilities one of the largest controllable costs on a GMP site."),
        ("flame", "Steam for low-temperature work", "Coal, briquette, FO or PNG boilers often serve loads below 120 °C. That Scope 1 can be removed through change control on the utility, not the validated process."),
        ("shield", "Disclosure", "BRSR Core-format reporting and value-chain disclosure put your energy and emissions in your customers' reports as well as your own."),
        ("leaf", "Carbon markets", "India's Carbon Credit Trading Scheme sets emission-intensity targets sector by sector. Sites that measure now are ready when their sector or supply chain is covered."),
    ],
    chain_eb="KSM to cold chain",
    chain_h="Every utility<br>has a lever.",
    chain_p="Starting materials arrive, reactors run, dryers and cleanrooms hold spec, water loops stay hot, packs leave in the cold chain. jouleWise acts at ten points — in the power supply and the utility block, never inside the validated process.",
    marks=[
        (1, "power", "Green sourcing", "Intrastate and ISTS solar and wind contracted through open access for a flat, round-the-clock load."),
        (2, "power", "Connectivity and metering", "Open access approvals, connection agreement and ABT metering at the site incomer."),
        (3, "power", "Rooftop solar", "Warehouse and admin roofs carry behind-the-meter solar, sized from measured load."),
        (4, "power", "Battery storage", "LFP storage for peak shaving and ride-through on critical HVAC and water systems."),
        (5, "heat", "Heat pumps on jacket and water loops", "Hot water for reactor jackets and utility loops made by heat pumps instead of boiler steam."),
        (6, "heat", "Cleanroom HVAC reheat", "AHU reheat and dehumidification coils fed from the heat pump hot-water circuit."),
        (7, "heat", "Hot-water store and PW loop", "Thermal store charged in solar blocks; purified-water loop held at sanitisation temperature."),
        (8, "heat", "Chiller heat recovery", "Heat that cooling towers throw away becomes the heat pump source — cooling and heating from one kWh."),
        (9, "data", "ergOS control", "15-minute metering of power, heat, chilled water, fuel and water; forecasting, trading and heat dispatch."),
        (10, "esg", "Suppliers and customers", "Starting-material and solvent data for Scope 3; customer questionnaires and per-batch carbon from esgOS."),
    ],
    power_p="Cleanroom HVAC, chillers and water systems run 24×7, so the load is high and flat. That suits round-the-clock wind and storage — and heat pump load can still be concentrated into solar hours with a hot-water store.",
    load=(84, 74, 20), shift=(7, 20), hp_window=(9, 16),
    heat_p="Much pharma heat is warm, not hot: jacket loops, dryer air, HVAC reheat, washing and purified-water sanitisation sit below 120 °C. Heat pumps serve those loads on electricity — and the chilled-water plant next door becomes their heat source.",
    heat_loads=[
        ("Reactor jacket heating", "hot-water loop", 60, 95),
        ("Solvent distillation and recovery", "most common solvents", 60, 110),
        ("Fluid-bed and tray dryers", "process air heating", 50, 90),
        ("Cleanroom HVAC reheat", "dehumidify, then reheat", 25, 45),
        ("Purified-water sanitisation", "hot storage and loop", 65, 85),
        ("CIP and washing", "vessels, bins, garments", 60, 85),
        ("Autoclaves and clean steam", "remain on existing steam", 121, 134),
        ("WFI multi-effect distillation", "remains on existing steam", 140, 180),
    ],
    heat_src="Chiller condensers and cooling-tower return, HVAC exhaust air, solvent-recovery condensers and warm effluent — heat the site already rejects.",
    heat_dual="Pharma sites cool and heat at once: chilled water for reactors and cleanrooms, reheat and hot loops alongside. A heat pump on the chilled-water return serves both from the same kWh.",
    cop=3.2, cop_note="hot water near 80 °C for jacket and water loops, drawn from the chilled-water return (heating side only; the cooling delivered is extra)",
    cockpit=dict(title="Site 1 · utilities + HVAC", tiles=[
        ("RE share MTD", "var(--green)", "61%", "var(--green)", "▲ open access"),
        ("Landed power", "var(--ink)", "₹5.6/kWh", "var(--green)", "▼ vs DISCOM"),
        ("HP COP heat + cool", "var(--heat)", "5.8", "var(--mute)", "HP-1 on CHW return"),
        ("Hot-water loop", "var(--heat)", "82 °C", "var(--mute)", "PW loop · in spec"),
        ("Steam avoided MTD", "var(--ink)", "310 t", "var(--green)", "▲ vs baseline"),
        ("CO₂ avoided MTD", "var(--ink)", "118 t", "var(--green)", "Scope 1 + 2"),
    ], ops=[
        ("var(--green)", "✓", "Day-ahead schedule sent to SLDC at 09:58"),
        ("var(--heat)", "●", "HP-1 recovering chilled-water heat for AHU reheat — block B"),
        ("var(--heat)", "●", "Hot-water store charging in solar blocks until 15:30"),
        ("var(--esg)", "!", "AHU-4 reheat energy +9% vs 30-day average — valve check raised"),
    ]),
    esg_out=[
        "BRSR and BRSR Core-format disclosures",
        "Customer supplier assessments — CDP supply chain, EcoVadis and audit questionnaires",
        "Carbon reduction plans for tenders and health-system procurement",
        "Carbon footprint per API, batch and pack",
        "Water intensity, solvent recovery and hazardous-waste tracking",
        "CDP climate response and assurance support",
        "Green attribute tracking — iREC eligibility for renewable consumption",
        "Emission-intensity baseline for the Carbon Credit Trading Scheme",
    ],
    roadmap2="RE-100 power plan, heat pump shortlist for jacket loops, HVAC reheat and water systems, and the ESG data map — in one business case.",
    roadmap4="One heat pump on the chilled-water return serving HVAC reheat and a hot-water loop, under change control; then jacket loops and dryers.",
)

COAL = ("Coal-fired boiler", "₹8,000/t · 4,000 kcal/kg · 75% efficiency", 8.0 / (4.65 * .75), 1.7 / (4.65 * .75), "#5d666c")

TEXTILE = dict(
    short="Textile", slug="textile", scene="textile",
    cover_h2="For textile mills and processing houses.",
    cover_p="One provider for green power, green heat and the data that proves both — from spinning floor to dye house to export container.",
    exec=dict(
        headline="Most of your heat<br>" + G % "is below 100 °C.",
        situation="A textile processing unit runs on hot water. Desizing, scouring, bleaching, dyeing and washing heat large volumes of water to 40–98 °C, mostly with coal, biomass or PNG boilers and thermic fluid heaters — then send that water, still warm, to the effluent plant. Many global brands have committed to phasing coal out of their tier 1 and tier 2 supply chains, and ask mills for renewable power and Scope 1 and 2 data.",
        value="Up to 25% lower power cost on DISCOM tariff and up to 65% renewable share (reported, year 1 of ergOS). Heat pumps then recover heat from warm effluent and deliver dye-house hot water — on green power, cheaper than coal-fired heat and close to zero-carbon.",
        first="A four-week decarbonisation baseline on one mill: power bills, load survey, coal and fuel records, and portable heat metering on dyeing, washing and effluent streams — ending in one business case for power, heat and ESG.",
    ),
    why_h="Your brands are<br>" + G % "phasing out coal.",
    why_p="For a spinner, weaver or processor, decarbonisation now decides which brand programmes you stay in. Six pressures point at the same metered data.",
    drivers=[
        ("users", "Brand supplier targets", "Global apparel and home-textile brands have set supply-chain emission targets and ask tier 1 and tier 2 mills for renewable power, Scope 1 and 2 data and a coal exit plan."),
        ("flame", "Coal phase-out", "Coal-fired boilers and thermic fluid heaters are the single largest source of a mill's emissions — and the first thing brand audits ask about."),
        ("globe", "EU product rules", "The EU's ecodesign rules are moving textiles towards digital product passports that carry environmental data back to the mill."),
        ("rupee", "Heat and power cost", "Hot water and drying are the largest energy costs in wet processing; spinning and weaving run three shifts on power. Both go straight to margin."),
        ("box", "Water and effluent", "ZLD and discharge norms tie water, heat and chemicals together. Cooler, cleaner effluent helps the ETP as well as the heat balance."),
        ("leaf", "Carbon markets", "Textiles is among the sectors named for emission-intensity targets under India's Carbon Credit Trading Scheme. Mills that measure now are ready."),
    ],
    chain_eb="Fibre to export",
    chain_h="Every bath<br>has a lever.",
    chain_p="Bales arrive, yarn is spun and woven, fabric is scoured, dyed, washed and dried, finished goods leave in containers. jouleWise acts at ten points — most of them on hot water.",
    marks=[
        (1, "power", "Green sourcing", "Intrastate and ISTS solar and wind contracted through open access for a three-shift load."),
        (2, "power", "Connectivity and metering", "Open access approvals, connection agreement and ABT metering at the mill incomer."),
        (3, "power", "Rooftop solar", "Spinning and warehouse roofs carry behind-the-meter solar, sized from measured load."),
        (4, "power", "Battery storage", "LFP storage for peak shaving and to keep spinning frames and humidification steady."),
        (5, "heat", "Heat pumps on dye-house water", "Hot water for scouring, bleaching, dyeing and washing made by heat pumps instead of coal steam."),
        (6, "heat", "Effluent heat recovery", "Warm dye and wash effluent becomes the heat pump source — and reaches the ETP cooler."),
        (7, "heat", "Hot-water store", "Store charged in solar blocks and drawn batch by batch across the day."),
        (8, "heat", "Stenter exhaust recovery", "Stenters stay on thermic fluid; their exhaust heat is recovered into the hot-water circuit."),
        (9, "data", "ergOS control", "15-minute metering of power, steam, hot water, fuel and water — per machine where it matters."),
        (10, "esg", "Brands and exports", "Brand questionnaires, coal-exit evidence and per-kg fabric carbon from esgOS."),
    ],
    power_p="Spinning and weaving run three shifts with humidification and compressed air; processing adds pumps, jets and dryers. The load is high day and night — heat pump load moves into solar hours with a hot-water store.",
    load=(88, 72, 26), shift=(6, 22), hp_window=(9, 16),
    heat_p="Wet processing is a hot-water business: most baths run between 40 and 98 °C, well inside heat pump range. The high-temperature exceptions — HT polyester dyeing and stenters — stay on steam or thermic fluid, with their exhaust heat recovered.",
    heat_loads=[
        ("Desizing and scouring", "cotton preparation", 60, 95),
        ("Peroxide bleaching", "continuous or batch", 80, 98),
        ("Reactive dyeing", "cotton and blends", 40, 80),
        ("Washing-off and soaping", "after dyeing", 60, 95),
        ("Size cooking", "weaving preparation", 75, 90),
        ("Process water preheat", "make-up and rinse water", 20, 60),
        ("HT disperse dyeing", "polyester · remains on steam", 125, 135),
        ("Stenters and dryers", "thermic fluid · exhaust recovered", 150, 200),
    ],
    heat_src="Warm effluent from dye and wash baths, stenter exhaust, condensate and air-compressor heat — much of a mill's heat currently goes down the drain.",
    heat_dual_t="Effluent as the source",
    heat_dual="Effluent at 40–60 °C is an excellent heat pump source: the small temperature lift means a high COP, and cooler effluent eases the load on the ETP.",
    cop=3.8, cop_note="hot water near 85 °C drawn from warm dye-house effluent",
    extra_fuels=[COAL],
    extra_note=" Coal: ₹8,000/t, 4,000 kcal/kg (4.65 kWh/kg), 1.7 kg CO₂/kg, 75% boiler efficiency.",
    cockpit=dict(title="Mill 1 · dye house + utilities", tiles=[
        ("RE share MTD", "var(--green)", "58%", "var(--green)", "▲ open access"),
        ("Landed power", "var(--ink)", "₹5.3/kWh", "var(--green)", "▼ vs DISCOM"),
        ("Heat pump COP", "var(--heat)", "3.9", "var(--mute)", "effluent source"),
        ("Hot-water store", "var(--heat)", "86 °C", "var(--mute)", "charged · solar block"),
        ("Coal avoided MTD", "var(--ink)", "380 t", "var(--green)", "▲ vs baseline"),
        ("CO₂ avoided MTD", "var(--ink)", "690 t", "var(--green)", "Scope 1 + 2"),
    ], ops=[
        ("var(--green)", "✓", "Day-ahead schedule sent to SLDC at 09:58"),
        ("var(--heat)", "●", "HP-1 drawing heat from equalisation tank at 48 °C"),
        ("var(--heat)", "●", "Hot-water store charging in solar blocks until 15:30"),
        ("var(--esg)", "!", "Jet J-7 water per kg fabric +11% vs recipe — owner notified"),
    ]),
    esg_out=[
        "BRSR and BRSR Core-format disclosures",
        "Brand and platform questionnaires — Higg FEM, CDP supply chain",
        "Coal-exit plan and renewable heat evidence for brand audits",
        "Carbon footprint per kg of fabric and per garment",
        "Water, chemical and effluent compliance data",
        "Digital product passport readiness for EU ecodesign rules",
        "Green attribute tracking — iREC eligibility for renewable consumption",
        "Emission-intensity baseline for the Carbon Credit Trading Scheme",
    ],
    roadmap2="RE-100 power plan, heat pump shortlist for dyeing, washing and effluent recovery, and the ESG data map — in one business case.",
    roadmap4="One effluent-source heat pump and hot-water store on the dye house, metered on ergOS; then washing ranges, bleaching and stenter exhaust.",
)

LPG = ("LPG-fired heater", "₹95/kg · 85% efficiency", 95 / (12.8 * .85), 2.98 / (12.8 * .85), "#5d666c")

HOTELS = dict(
    short="Hotels", slug="hotels", scene="hotel",
    cover_h2="For hotels and hospitality portfolios.",
    cover_p="One provider for green power, green heat and the data that proves both — from the chiller plant to guest-room showers to the laundry.",
    exec=dict(
        headline="Your chillers throw away<br>" + G % "your hot water.",
        situation="A hotel runs a small utility plant 365 days a year: chillers for comfort, hot water for rooms, kitchens and laundry, pool heating, and DG sets for outages. Hot water and laundry usually burn LPG, PNG or diesel, while the chillers next to them reject heat through cooling towers. Corporate travel buyers, owners and lenders increasingly ask for carbon per room night.",
        value="Up to 25% lower power cost on DISCOM tariff and up to 65% renewable share (reported, year 1 of ergOS). Heat-recovery heat pumps then make guest hot water from chiller heat — cooling and hot water from one kWh — and batteries cut DG hours.",
        first="A four-week decarbonisation baseline on one property: power bills, DG and fuel logs, and portable heat metering on hot water, laundry and the pool — ending in one business case for the property and a template for the portfolio.",
    ),
    why_h="Your guests' employers<br>" + G % "count the room night.",
    why_p="For a hotel or hospitality group, energy and carbon now show up in corporate RFPs, certifications and owner reporting. Six pressures point at the same metered data.",
    drivers=[
        ("users", "Corporate travel buyers", "Corporate travel programmes increasingly ask for carbon and energy per occupied room night before they sign rate agreements."),
        ("globe", "Certifications and platforms", "Green building ratings and sustainability badges on booking platforms all rest on metered energy and water data."),
        ("rupee", "Energy cost", "Hotels usually pay commercial tariffs, among the highest per unit — and run chillers, hot water and laundry every day of the year."),
        ("flame", "LPG, diesel and DG", "Hot water, laundry and pools run on LPG, PNG or diesel, and DG sets cover outages. Heat pumps and batteries replace most of that fuel."),
        ("shield", "Owners and lenders", "Owners, investors and lenders want asset-level energy and carbon data; green finance prices it in. Listed groups also report BRSR Core-format data."),
        ("leaf", "Guest expectation", "Guests notice towel cards; they notice a hotel that runs on green power more. The claim needs a meter behind it."),
    ],
    chain_eb="Arrival to laundry",
    chain_h="Every room night<br>has a lever.",
    chain_p="Guests arrive, rooms need hot water, kitchens cook, laundry runs, the pool stays warm and chillers keep it all cool. jouleWise acts at eleven points across the property — and repeats the plan across the portfolio.",
    marks=[
        (1, "power", "Green sourcing", "Intrastate and ISTS solar and wind through green open access — eligible from 100 kW under the 2022 rules, subject to state regulations."),
        (2, "power", "Connectivity and metering", "Open access approvals, connection agreement and ABT metering at the property incomer."),
        (3, "power", "Rooftop solar", "Podium and service roofs carry behind-the-meter solar, sized from measured load."),
        (4, "power", "Battery storage", "LFP storage replaces most DG hours and shaves the evening peak."),
        (5, "heat", "Heat pumps for guest hot water", "Rooms, kitchens and spa hot water from heat pumps and a legionella-safe store."),
        (6, "heat", "Laundry", "Washers and heat-pump dryers on the hot-water circuit; ironers stay on steam or gas."),
        (7, "heat", "Pool and spa", "Pool held at temperature by heat pumps instead of LPG or diesel heaters."),
        (8, "heat", "Chiller heat recovery", "Chiller condenser heat becomes guest hot water — cooling and hot water from one kWh."),
        (9, "data", "ergOS control", "15-minute metering of power, hot water, chilled water, fuel and water; forecasting and dispatch."),
        (10, "esg", "Guests, buyers and owners", "Carbon per room night for corporate RFPs, certifications and owner reporting from esgOS."),
        (11, "power", "EV charging", "Guest and fleet EV chargers on green power, metered and billed on ergOS."),
    ],
    power_p="Hotels carry a steady load with an evening peak — chillers, lifts, kitchens and lighting. Green open access is available from 100 kW under the Green Energy Open Access Rules, 2022, subject to state regulations, and properties in one state can be planned together. Batteries take over DG hours.",
    load=(80, 56, 18), shift=(7, 23), hp_window=(10, 16),
    heat_p="Almost all hotel heat is low-temperature: showers, dishwashing, laundry and the pool sit between 26 and 82 °C. Heat pumps are built for this — and the chillers already on site supply the heat.",
    heat_loads=[
        ("Guest-room hot water", "stored at 60 °C+ for legionella control", 55, 65),
        ("Kitchen dishwashing", "wash and final rinse", 60, 82),
        ("Laundry washers", "linen and uniforms", 40, 80),
        ("Tumble dryers", "heat-pump dryers available", 60, 90),
        ("Pool and spa", "water and hall air", 26, 40),
        ("HVAC reheat and fresh air", "humidity control", 25, 45),
        ("Flatwork ironers", "remain on steam or gas", 150, 180),
        ("Cooking", "remains on PNG, LPG or induction", 180, 200),
    ],
    heat_src="Chiller condensers, kitchen and laundry exhaust, and warm grey water — a hotel rejects nearly as much heat as it buys.",
    heat_dual="Hotels cool all year while making hot water all day. A heat pump on the chiller circuit delivers both, so the cooling you already pay for produces your hot water.",
    cop=3.5, cop_note="hot water near 60 °C for guest rooms, drawn from the chiller condenser loop",
    extra_fuels=[LPG],
    extra_note=" LPG: ₹95/kg, 12.8 kWh/kg, 2.98 kg CO₂/kg. Hotels on commercial tariffs may pay more than ₹8.5/kWh from the DISCOM, which strengthens the case for green open access.",
    cockpit=dict(title="Property 1 · central plant", tiles=[
        ("RE share MTD", "var(--green)", "55%", "var(--green)", "▲ open access"),
        ("Landed power", "var(--ink)", "₹6.4/kWh", "var(--green)", "▼ vs commercial tariff"),
        ("HP COP heat + cool", "var(--heat)", "6.1", "var(--mute)", "HP-1 on chiller loop"),
        ("Hot-water store", "var(--heat)", "63 °C", "var(--mute)", "legionella-safe"),
        ("LPG avoided MTD", "var(--ink)", "7,800 kg", "var(--green)", "▲ vs baseline"),
        ("CO₂ avoided MTD", "var(--ink)", "64 t", "var(--green)", "Scope 1 + 2"),
    ], ops=[
        ("var(--green)", "✓", "Day-ahead schedule sent to SLDC at 09:58"),
        ("var(--heat)", "●", "HP-1 recovering chiller heat for guest-room hot water"),
        ("var(--heat)", "●", "Pool held at 29 °C on heat pump — LPG heater idle"),
        ("var(--esg)", "!", "Laundry kWh per kg linen +8% vs 30-day average — ironer steam trap check"),
    ]),
    esg_out=[
        "BRSR and BRSR Core-format disclosures for listed groups",
        "Carbon and energy per occupied room night for corporate RFPs",
        "Evidence packs for green building and sustainability certifications",
        "Owner, investor and lender asset-level reporting",
        "Water per guest night, food waste and single-use plastics tracking",
        "CDP climate response and assurance support",
        "Green attribute tracking — iREC eligibility for renewable consumption",
        "Refrigerant inventory and leak tracking for chillers",
    ],
    roadmap2="Green power plan across properties, heat pump shortlist for guest hot water, laundry and pool, and the ESG data map — in one business case.",
    roadmap4="One heat-recovery heat pump and store on guest-room hot water at a pilot property; then laundry, pool and the rest of the portfolio.",
    subs=[("Tell us the plant.", "Tell us the property."), ("Most plants buy", "Most properties buy"), ("for your plant.", "for your property."),
          ("Plants ready to contract", "Properties ready to contract"), ("Plants with capex budget", "Properties with capex budget"),
          ("Plants that want green steam now", "Properties that want green heat now"), ("Multi-plant groups", "Multi-property groups"),
          ("Hot water and low-pressure steam delivered to your header.", "Hot water delivered to your plant room."),
          ("heat pump range · hot water and steam", "heat pump range · hot water"),
          ("fulfil industrial demand at least cost", "fulfil the property's demand at least cost")],
)

BEVERAGES = dict(
    short="Beverages", slug="beverages", scene="beverages",
    cover_h2="For beverage and bottling plants.",
    cover_p="One provider for green power, green heat and the data that proves both — from source water to CIP to the last case on the truck.",
    exec=dict(
        headline="Chill it, heat it —<br>" + G % "on the same kWh.",
        situation="A beverage plant cools and heats all day: chillers for carbonation, syrup and cold rooms; hot water for CIP, bottle washing, syrup and pasteurisation, mostly from PNG, diesel or biomass boilers. Blow moulders and compressors add a heavy power load. Brand owners and franchise partners set renewable and emission targets for their bottling network, and plastic EPR adds another annual filing.",
        value="Up to 25% lower power cost on DISCOM tariff and up to 65% renewable share (reported, year 1 of ergOS). Heat pumps on the chiller loop then deliver CIP, washing and pasteuriser hot water from heat the plant already rejects.",
        first="A four-week decarbonisation baseline on one plant: power bills, load survey, fuel records and portable heat metering on CIP, bottle washing and pasteurisation — ending in one business case for power, heat and ESG.",
    ),
    why_h="Your brand owner<br>" + G % "counts every litre.",
    why_p="For a bottler or beverage maker, carbon, water and plastic are now scored per litre by brand owners, retailers and regulators. Six pressures point at the same metered data.",
    drivers=[
        ("users", "Brand-owner targets", "Brand owners and franchise partners set renewable and emission targets for their bottling network and ask for metered proof, plant by plant."),
        ("box", "Plastic EPR", "Plastic Waste Management rules set EPR and recycled-content obligations on PET packaging, tracked and filed every year."),
        ("globe", "Water", "Water-use ratio and groundwater permits are licence-to-operate issues for bottlers — and belong on the same data platform as energy."),
        ("rupee", "Energy cost", "Chilling, compressed air, blow moulding and hot water for CIP and washing — and summer peaks that push every one of them up."),
        ("shield", "Disclosure", "BRSR Core-format reporting and value-chain disclosure put your energy, water and plastics in customers' reports as well as your own."),
        ("leaf", "Carbon markets", "India's Carbon Credit Trading Scheme sets emission-intensity targets sector by sector. Plants that measure now are ready when their sector or supply chain is covered."),
    ],
    chain_eb="Source water to shelf",
    chain_h="Every litre<br>has a lever.",
    chain_p="Water is treated, syrup is made, bottles are washed, filled, pasteurised and chilled, and cases leave for the market. jouleWise acts at eleven points across the plant.",
    marks=[
        (1, "power", "Green sourcing", "Intrastate and ISTS solar and wind contracted through open access for a long-shift load with summer peaks."),
        (2, "power", "Connectivity and metering", "Open access approvals, connection agreement and ABT metering at the plant incomer."),
        (3, "power", "Rooftop solar", "Bottling hall and warehouse roofs carry behind-the-meter solar, sized from measured load."),
        (4, "power", "Battery storage", "LFP storage shaves the blow-moulding and chiller peak and carries solar into the evening shift."),
        (5, "heat", "Heat pumps on CIP and syrup", "CIP, syrup dissolving and process hot water from heat pumps instead of boiler steam."),
        (6, "heat", "Pasteuriser and bottle washer", "Tunnel pasteuriser zones and washer baths on the heat pump hot-water circuit."),
        (7, "heat", "CIP and hot-water store", "Store charged in solar blocks, ready for every CIP cycle and changeover."),
        (8, "heat", "Chiller heat recovery", "Carbonation and process-chiller heat becomes the heat pump source — chilling and hot water from one kWh."),
        (9, "data", "ergOS control", "15-minute metering of power, heat, chilled water, fuel and water — per line where it matters."),
        (10, "esg", "Outbound and packaging", "Carbon per litre and per case, plastic EPR returns and recycled-content tracking from esgOS."),
        (11, "esg", "Source water", "Water withdrawal by source, water-use ratio and groundwater compliance, metered and reported."),
    ],
    power_p="Blow moulders, compressors, chillers and filling lines run long shifts with a daytime peak — and demand climbs steeply in summer. We build the green portfolio to that profile and move heat pump load into solar hours.",
    load=(92, 48, 22), shift=(6, 22), hp_window=(9, 16),
    heat_p="Almost every heat duty in a beverage plant sits below 100 °C: CIP, washing, syrup and pasteurisation. Heat pumps serve them on electricity — and the chillers cooling the product supply the heat.",
    heat_loads=[
        ("Bottle washing", "returnable glass, caustic baths", 60, 85),
        ("CIP of syrup and filler lines", "hot caustic and rinse", 70, 85),
        ("Syrup dissolving", "sugar and ingredients", 60, 85),
        ("Tunnel pasteurisation", "packed product", 60, 75),
        ("Hot fill and flash pasteurisation", "juices, teas, dairy drinks", 72, 95),
        ("Crate and case washing", "returnable logistics", 50, 70),
        ("UHT processing", "remains on existing steam", 135, 145),
    ],
    heat_src="Carbonation, process and cold-room chiller condensers, compressor heat and warm rinse water — heat the plant already rejects every hour it runs.",
    heat_dual="Beverage plants chill product while heating CIP and wash water. A heat pump on the chiller loop serves both from the same kWh.",
    cop=3.6, cop_note="hot water near 80 °C for CIP and washing, drawn from the carbonation and process chiller loop",
    cockpit=dict(title="Plant 1 · utilities + line 2", tiles=[
        ("RE share MTD", "var(--green)", "63%", "var(--green)", "▲ open access"),
        ("Landed power", "var(--ink)", "₹5.5/kWh", "var(--green)", "▼ vs DISCOM"),
        ("HP COP heat + cool", "var(--heat)", "5.4", "var(--mute)", "chiller loop source"),
        ("CIP tank", "var(--heat)", "82 °C", "var(--mute)", "ready · line 2"),
        ("PNG avoided MTD", "var(--ink)", "36,500 SCM", "var(--green)", "▲ vs baseline"),
        ("CO₂ avoided MTD", "var(--ink)", "92 t", "var(--green)", "Scope 1 + 2"),
    ], ops=[
        ("var(--green)", "✓", "Day-ahead schedule sent to SLDC at 09:58"),
        ("var(--heat)", "●", "HP-1 recovering carbonation-chiller heat for CIP"),
        ("var(--heat)", "●", "Tunnel pasteuriser zone 3 running on heat pump water"),
        ("var(--esg)", "!", "Line 2 water-use ratio 1.9 L/L vs 1.7 target — owner notified"),
    ]),
    esg_out=[
        "BRSR and BRSR Core-format disclosures",
        "Brand-owner and franchise scorecards; CDP supply chain",
        "Plastic EPR returns and recycled-content tracking",
        "Water withdrawal, water-use ratio and groundwater compliance",
        "Carbon footprint per litre and per case",
        "Refrigerant inventory for ammonia and HFC chillers",
        "Green attribute tracking — iREC eligibility for renewable consumption",
        "Emission-intensity baseline for the Carbon Credit Trading Scheme",
    ],
    roadmap2="RE-100 power plan, heat pump shortlist for CIP, washing and pasteurisation, and the ESG data map — in one business case.",
    roadmap4="One heat pump on the chiller loop with a CIP hot-water store, metered on ergOS; then washers, pasteurisers and syrup.",
)

ALL = [AUTO, PHARMA, TEXTILE, HOTELS, BEVERAGES]
